interface CountryType {
  country_code: string;
  label: string;
  suggested?: boolean;
}

export const Countries: CountryType[] = [
  { country_code: 'AD', label: 'Andorra' },
  {
    country_code: 'AE',
    label: 'Emiratos Árabes Unidos',
  },
  { country_code: 'AF', label: 'Afganistán' },
  {
    country_code: 'AG',
    label: 'Antigua y Barbuda',
  },
  { country_code: 'AI', label: 'Anguila' },
  { country_code: 'AL', label: 'Albania' },
  { country_code: 'AM', label: 'Armenia' },
  { country_code: 'AO', label: 'Angola' },
  { country_code: 'AQ', label: 'Antártida' },
  { country_code: 'AR', label: 'Argentina' },
  { country_code: 'AS', label: 'Samoa Americana' },
  { country_code: 'AT', label: 'Austria' },
  {
    country_code: 'AU',
    label: 'Australia',
  },
  { country_code: 'AW', label: 'Aruba' },
  { country_code: 'AX', label: 'Islas Aland' },
  { country_code: 'AZ', label: 'Azerbaiyán' },
  {
    country_code: 'BA',
    label: 'Bosnia y Herzegovina',
  },
  { country_code: 'BB', label: 'Barbados' },
  { country_code: 'BD', label: 'Bangladesh' },
  { country_code: 'BE', label: 'Bélgica' },
  { country_code: 'BF', label: 'Burkina Faso' },
  { country_code: 'BG', label: 'Bulgaria' },
  { country_code: 'BH', label: 'Bahrein' },
  { country_code: 'BI', label: 'Burundi' },
  { country_code: 'BJ', label: 'Benín' },
  { country_code: 'BL', label: 'San Bartolomé' },
  { country_code: 'BM', label: 'Bermuda' },
  { country_code: 'BN', label: 'Brunéi Darussalam' },
  { country_code: 'BO', label: 'Bolivia' },
  { country_code: 'BR', label: 'Brasil' },
  { country_code: 'BS', label: 'Bahamas' },
  { country_code: 'BT', label: 'Bután' },
  { country_code: 'BV', label: 'Isla Bouvet' },
  { country_code: 'BW', label: 'Botsuana' },
  { country_code: 'BY', label: 'Bielorrusia' },
  { country_code: 'BZ', label: 'Belice' },
  {
    country_code: 'CA',
    label: 'Canadá',
  },
  {
    country_code: 'CC',
    label: 'Islas Cocos (Keeling)',
  },
  {
    country_code: 'CD',
    label: 'República Democrática del Congo',
  },
  {
    country_code: 'CF',
    label: 'República Centroafricana',
  },
  {
    country_code: 'CG',
    label: 'República del Congo',
  },
  { country_code: 'CH', label: 'Suiza' },
  { country_code: 'CI', label: "Cote d'Ivoire" },
  { country_code: 'CK', label: 'Cook Islands' },
  { country_code: 'CL', label: 'Chile' },
  { country_code: 'CM', label: 'Cameroon' },
  { country_code: 'CN', label: 'China' },
  { country_code: 'CO', label: 'Colombia' },
  { country_code: 'CR', label: 'Costa Rica' },
  { country_code: 'CU', label: 'Cuba' },
  { country_code: 'CV', label: 'Cape Verde' },
  { country_code: 'CW', label: 'Curacao' },
  { country_code: 'CX', label: 'Isla de Navidad' },
  { country_code: 'CY', label: 'Chipre' },
  { country_code: 'CZ', label: 'República Checa' },
  {
    country_code: 'DE',
    label: 'Alemania',
  },
  { country_code: 'DJ', label: 'Djibouti' },
  { country_code: 'DK', label: 'Denmark' },
  { country_code: 'DM', label: 'Dominica' },
  {
    country_code: 'DO',
    label: 'República Dominicana',
  },
  { country_code: 'DZ', label: 'Algeria' },
  { country_code: 'EC', label: 'Ecuador' },
  { country_code: 'EE', label: 'Estonia' },
  { country_code: 'EG', label: 'Egipto' },
  { country_code: 'EH', label: 'Western Sahara' },
  { country_code: 'ER', label: 'Eritrea' },
  { country_code: 'ES', label: 'España' },
  { country_code: 'ET', label: 'Ethiopia' },
  { country_code: 'FI', label: 'Finland' },
  { country_code: 'FJ', label: 'Fiji' },
  {
    country_code: 'FK',
    label: 'Falkland Islands (Malvinas)',
  },
  {
    country_code: 'FM',
    label: 'Micronesia, Federated States of',
  },
  { country_code: 'FO', label: 'Faroe Islands' },
  {
    country_code: 'FR',
    label: 'France',
  },
  { country_code: 'GA', label: 'Gabon' },
  { country_code: 'GB', label: 'United Kingdom' },
  { country_code: 'GD', label: 'Grenada' },
  { country_code: 'GE', label: 'Georgia' },
  { country_code: 'GF', label: 'French Guiana' },
  { country_code: 'GG', label: 'Guernsey' },
  { country_code: 'GH', label: 'Ghana' },
  { country_code: 'GI', label: 'Gibraltar' },
  { country_code: 'GL', label: 'Greenland' },
  { country_code: 'GM', label: 'Gambia' },
  { country_code: 'GN', label: 'Guinea' },
  { country_code: 'GP', label: 'Guadeloupe' },
  { country_code: 'GQ', label: 'Equatorial Guinea' },
  { country_code: 'GR', label: 'Greece' },
  {
    country_code: 'GS',
    label: 'South Georgia and the South Sandwich Islands',
  },
  { country_code: 'GT', label: 'Guatemala' },
  { country_code: 'GU', label: 'Guam' },
  { country_code: 'GW', label: 'Guinea-Bissau' },
  { country_code: 'GY', label: 'Guyana' },
  { country_code: 'HK', label: 'Hong Kong' },
  {
    country_code: 'HM',
    label: 'Heard Island and McDonald Islands',
  },
  { country_code: 'HN', label: 'Honduras' },
  { country_code: 'HR', label: 'Croatia' },
  { country_code: 'HT', label: 'Haiti' },
  { country_code: 'HU', label: 'Hungary' },
  { country_code: 'ID', label: 'Indonesia' },
  { country_code: 'IE', label: 'Ireland' },
  { country_code: 'IL', label: 'Israel' },
  { country_code: 'IM', label: 'Isle of Man' },
  { country_code: 'IN', label: 'India' },
  {
    country_code: 'IO',
    label: 'British Indian Ocean Territory',
  },
  { country_code: 'IQ', label: 'Iraq' },
  {
    country_code: 'IR',
    label: 'Iran, Islamic Republic of',
  },
  { country_code: 'IS', label: 'Iceland' },
  { country_code: 'IT', label: 'Italy' },
  { country_code: 'JE', label: 'Jersey' },
  { country_code: 'JM', label: 'Jamaica' },
  { country_code: 'JO', label: 'Jordan' },
  {
    country_code: 'JP',
    label: 'Japan',
  },
  { country_code: 'KE', label: 'Kenya' },
  { country_code: 'KG', label: 'Kyrgyzstan' },
  { country_code: 'KH', label: 'Cambodia' },
  { country_code: 'KI', label: 'Kiribati' },
  { country_code: 'KM', label: 'Comoros' },
  {
    country_code: 'KN',
    label: 'Saint Kitts and Nevis',
  },
  {
    country_code: 'KP',
    label: "Korea, Democratic People's Republic of",
  },
  { country_code: 'KR', label: 'Korea, Republic of' },
  { country_code: 'KW', label: 'Kuwait' },
  { country_code: 'KY', label: 'Cayman Islands' },
  { country_code: 'KZ', label: 'Kazakhstan' },
  {
    country_code: 'LA',
    label: "Lao People's Democratic Republic",
  },
  { country_code: 'LB', label: 'Lebanon' },
  { country_code: 'LC', label: 'Saint Lucia' },
  { country_code: 'LI', label: 'Liechtenstein' },
  { country_code: 'LK', label: 'Sri Lanka' },
  { country_code: 'LR', label: 'Liberia' },
  { country_code: 'LS', label: 'Lesotho' },
  { country_code: 'LT', label: 'Lithuania' },
  { country_code: 'LU', label: 'Luxembourg' },
  { country_code: 'LV', label: 'Latvia' },
  { country_code: 'LY', label: 'Libya' },
  { country_code: 'MA', label: 'Morocco' },
  { country_code: 'MC', label: 'Monaco' },
  {
    country_code: 'MD',
    label: 'Moldova, Republic of',
  },
  { country_code: 'ME', label: 'Montenegro' },
  {
    country_code: 'MF',
    label: 'Saint Martin (French part)',
  },
  { country_code: 'MG', label: 'Madagascar' },
  { country_code: 'MH', label: 'Marshall Islands' },
  {
    country_code: 'MK',
    label: 'Macedonia, the Former Yugoslav Republic of',
  },
  { country_code: 'ML', label: 'Mali' },
  { country_code: 'MM', label: 'Myanmar' },
  { country_code: 'MN', label: 'Mongolia' },
  { country_code: 'MO', label: 'Macao' },
  {
    country_code: 'MP',
    label: 'Northern Mariana Islands',
  },
  { country_code: 'MQ', label: 'Martinique' },
  { country_code: 'MR', label: 'Mauritania' },
  { country_code: 'MS', label: 'Montserrat' },
  { country_code: 'MT', label: 'Malta' },
  { country_code: 'MU', label: 'Mauritius' },
  { country_code: 'MV', label: 'Maldives' },
  { country_code: 'MW', label: 'Malawi' },
  { country_code: 'MX', label: 'Mexico' },
  { country_code: 'MY', label: 'Malaysia' },
  { country_code: 'MZ', label: 'Mozambique' },
  { country_code: 'NA', label: 'Namibia' },
  { country_code: 'NC', label: 'New Caledonia' },
  { country_code: 'NE', label: 'Niger' },
  { country_code: 'NF', label: 'Norfolk Island' },
  { country_code: 'NG', label: 'Nigeria' },
  { country_code: 'NI', label: 'Nicaragua' },
  { country_code: 'NL', label: 'Netherlands' },
  { country_code: 'NO', label: 'Norway' },
  { country_code: 'NP', label: 'Nepal' },
  { country_code: 'NR', label: 'Nauru' },
  { country_code: 'NU', label: 'Niue' },
  { country_code: 'NZ', label: 'New Zealand' },
  { country_code: 'OM', label: 'Oman' },
  { country_code: 'PA', label: 'Panama' },
  { country_code: 'PE', label: 'Peru' },
  { country_code: 'PF', label: 'French Polynesia' },
  { country_code: 'PG', label: 'Papua New Guinea' },
  { country_code: 'PH', label: 'Philippines' },
  { country_code: 'PK', label: 'Pakistan' },
  { country_code: 'PL', label: 'Polonia' },
  {
    country_code: 'PM',
    label: 'Saint Pierre and Miquelon',
  },
  { country_code: 'PN', label: 'Pitcairn' },
  { country_code: 'PR', label: 'Puerto Rico' },
  {
    country_code: 'PS',
    label: 'Palestine, State of',
  },
  { country_code: 'PT', label: 'Portugal' },
  { country_code: 'PW', label: 'Palau' },
  { country_code: 'PY', label: 'Paraguay' },
  { country_code: 'QA', label: 'Qatar' },
  { country_code: 'RE', label: 'Reunion' },
  { country_code: 'RO', label: 'Romania' },
  { country_code: 'RS', label: 'Serbia' },
  { country_code: 'RU', label: 'Russian Federation' },
  { country_code: 'RW', label: 'Rwanda' },
  { country_code: 'SA', label: 'Saudi Arabia' },
  { country_code: 'SB', label: 'Solomon Islands' },
  { country_code: 'SC', label: 'Seychelles' },
  { country_code: 'SD', label: 'Sudan' },
  { country_code: 'SE', label: 'Sweden' },
  { country_code: 'SG', label: 'Singapore' },
  { country_code: 'SH', label: 'Saint Helena' },
  { country_code: 'SI', label: 'Slovenia' },
  {
    country_code: 'SJ',
    label: 'Svalbard and Jan Mayen',
  },
  { country_code: 'SK', label: 'Slovakia' },
  { country_code: 'SL', label: 'Sierra Leone' },
  { country_code: 'SM', label: 'San Marino' },
  { country_code: 'SN', label: 'Senegal' },
  { country_code: 'SO', label: 'Somalia' },
  { country_code: 'SR', label: 'Suriname' },
  { country_code: 'SS', label: 'South Sudan' },
  {
    country_code: 'ST',
    label: 'Sao Tome and Principe',
  },
  { country_code: 'SV', label: 'El Salvador' },
  {
    country_code: 'SX',
    label: 'Sint Maarten (Dutch part)',
  },
  {
    country_code: 'SY',
    label: 'Syrian Arab Republic',
  },
  { country_code: 'SZ', label: 'Swaziland' },
  {
    country_code: 'TC',
    label: 'Turks and Caicos Islands',
  },
  { country_code: 'TD', label: 'Chad' },
  {
    country_code: 'TF',
    label: 'French Southern Territories',
  },
  { country_code: 'TG', label: 'Togo' },
  { country_code: 'TH', label: 'Thailand' },
  { country_code: 'TJ', label: 'Tajikistan' },
  { country_code: 'TK', label: 'Tokelau' },
  { country_code: 'TL', label: 'Timor-Leste' },
  { country_code: 'TM', label: 'Turkmenistan' },
  { country_code: 'TN', label: 'Tunisia' },
  { country_code: 'TO', label: 'Tonga' },
  { country_code: 'TR', label: 'Turkey' },
  {
    country_code: 'TT',
    label: 'Trinidad and Tobago',
  },
  { country_code: 'TV', label: 'Tuvalu' },
  {
    country_code: 'TW',
    label: 'Taiwan',
  },
  {
    country_code: 'TZ',
    label: 'República Unida de Tanzania',
  },
  { country_code: 'UA', label: 'Ucrania' },
  { country_code: 'UG', label: 'Uganda' },
  {
    country_code: 'US',
    label: 'Estados Unidos',
  },
  { country_code: 'UY', label: 'Uruguay' },
  { country_code: 'UZ', label: 'Uzbekistán' },
  {
    country_code: 'VA',
    label: 'Santa Sede (Estado de la Ciudad del Vaticano)',
  },
  {
    country_code: 'VC',
    label: 'San Vicente y las Granadinas',
  },
  { country_code: 'VE', label: 'Venezuela' },
  {
    country_code: 'VG',
    label: 'British Virgin Islands',
  },
  {
    country_code: 'VI',
    label: 'US Virgin Islands',
  },
  { country_code: 'VN', label: 'Vietnam' },
  { country_code: 'VU', label: 'Vanuatu' },
  { country_code: 'WF', label: 'Wallis and Futuna' },
  { country_code: 'WS', label: 'Samoa' },
  { country_code: 'XK', label: 'Kosovo' },
  { country_code: 'YE', label: 'Yemen' },
  { country_code: 'YT', label: 'Mayotte' },
  { country_code: 'ZA', label: 'South Africa' },
  { country_code: 'ZM', label: 'Zambia' },
  { country_code: 'ZW', label: 'Zimbabwe' },
];
